// lib/bug-resolver/draft-pr.mjs
//
// Creates a DRAFT PR for a bug-resolver-generated patch. Wraps git +
// scripts/safe-gh-pr.sh (which forces --repo mitwilli-create/career-ops
// to close the 2026-05-20 cross-fork-leak gap).
//
// Inputs:
//   bugId       — e.g., "bug-2026-05-23-003" (used as branch name suffix)
//   patch       — unified diff string (already validated via git apply --check
//                 inside pipeline.mjs)
//   prMetadata  — { title, body_outline, test_plan, rollback_plan }
//   isDryRun    — optional; if true, returns what WOULD happen without writes
//
// Returns: { branchName, commitSha, prUrl, dryRun? }
// Throws: DraftPrError on any failure (dirty tree, wrong branch, patch fails,
//         push fails, gh create fails). Caller (orchestrator) should route the
//         bug to NEEDS_HUMAN with the error reason.

import { execSync } from 'node:child_process';
import { writeFileSync, unlinkSync, existsSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { isSensitivePath } from '../leak-guard.mjs';

const __filename = fileURLToPath(import.meta.url);
const REPO_ROOT = resolve(dirname(__filename), '..', '..');

export class DraftPrError extends Error {
  constructor(msg, phase) {
    super(msg);
    this.name = 'DraftPrError';
    this.phase = phase;
  }
}

// Helper: run git/gh commands with consistent options + clear error wrapping.
function run(cmd, options = {}) {
  return execSync(cmd, {
    encoding: 'utf-8',
    cwd: REPO_ROOT,
    timeout: 30_000,
    stdio: ['pipe', 'pipe', 'pipe'],
    ...options,
  });
}

function branchExists(branchName) {
  try {
    execSync(`git show-ref --verify --quiet refs/heads/${branchName}`, {
      cwd: REPO_ROOT,
      timeout: 5000,
      stdio: 'pipe',
    });
    return true;
  } catch {
    return false;
  }
}

function formatCommitMessage(bugId, prMetadata) {
  const title = (prMetadata.title || `bug-resolver: ${bugId}`).slice(0, 72);
  const body = [
    '',
    `Resolves ${bugId} via bug-resolver pipeline (Phase 2).`,
    '',
    `Test plan: ${(prMetadata.test_plan || 'manual review').slice(0, 200)}`,
  ].join('\n');
  return title + body;
}

function formatPrBody(bugId, prMetadata, autoMergeSafe = false) {
  const lines = [];
  lines.push(`**Bug ID:** \`${bugId}\``);
  lines.push(`**Generated by:** bug-resolver pipeline (Phase 2)`);
  if (autoMergeSafe) {
    lines.push(`**Auto-merge:** enabled (v2 — fires on CI green)`);
  } else {
    lines.push(`**Auto-merge:** disabled (human review required)`);
  }
  lines.push('');
  lines.push('## Summary');
  lines.push(prMetadata.body_outline || '(no outline provided)');
  lines.push('');
  lines.push('## Test plan');
  lines.push(prMetadata.test_plan || '(no test plan)');
  lines.push('');
  lines.push('## Rollback plan');
  lines.push(prMetadata.rollback_plan || 'git revert HEAD');
  lines.push('');
  lines.push('---');
  if (autoMergeSafe) {
    lines.push('🤖 v2 auto-merge PR — will merge automatically once CI passes. ' +
              'Cancel via `gh pr ready --undo <pr>` or close the PR.');
  } else {
    lines.push('🤖 DRAFT PR — Mitchell reviews before merge. Auto-merge blocked ' +
              '(sensitive paths touched OR auto-merge disabled at intake).');
  }
  return lines.join('\n');
}

// v2 (2026-05-25): given a list of touched file paths, returns the subset
// that match the cross-fork-leak sensitive-paths regex (cv.md, hm-intel,
// apply-pack[s], second-brain-extracted, etc). Used to gate auto-merge —
// PRs touching ANY sensitive path stay DRAFT-only regardless of CI state.
export function findSensitiveTouches(touchedFiles) {
  const matches = [];
  for (const f of touchedFiles) {
    // Resolve relative paths against repo root so the regex (which uses
    // absolute-path patterns) can match. Absolute paths pass through.
    const abs = f.startsWith('/') ? f : join(REPO_ROOT, f);
    if (isSensitivePath(abs)) matches.push(f);
  }
  return matches;
}

export async function createDraftPr({ bugId, patch, prMetadata, isDryRun = false, enableAutoMerge = false }) {
  if (!bugId) throw new DraftPrError('bugId is required', 'preflight');
  if (!patch || !patch.startsWith('diff --git')) {
    throw new DraftPrError('patch must be a non-empty unified diff starting with "diff --git"', 'preflight');
  }
  if (!prMetadata || !prMetadata.title) {
    throw new DraftPrError('prMetadata.title is required', 'preflight');
  }

  const branchName = `bug-resolver/${bugId}`;

  // 1. Pre-flight: no TRACKED modifications + on main + branch doesn't exist.
  // We only block on tracked-file changes (staged or unstaged) because untracked
  // files won't be touched by git apply and are present legitimately in this project.
  // EXCEPTION: data/bug-ledger.jsonl is allowlisted — the resolver writes IN_PROGRESS
  // to it BEFORE this preflight runs, so it's expected to be modified. The unstaged
  // ledger change won't be staged into the PR (we only `git add` files the patch touched).
  const trackedDiff = run('git diff HEAD --name-only').trim();
  const offending = trackedDiff
    .split('\n')
    .map(s => s.trim())
    .filter(s => s.length > 0)
    .filter(s => s !== 'data/bug-ledger.jsonl');
  if (offending.length > 0) {
    throw new DraftPrError(
      `Tracked files modified — stage or stash them before bug-resolver can create a PR.\nModified:\n${offending.join('\n').slice(0, 500)}`,
      'preflight'
    );
  }

  const currentBranch = run('git rev-parse --abbrev-ref HEAD').trim();
  if (currentBranch !== 'main') {
    throw new DraftPrError(`Expected to be on main, got "${currentBranch}"`, 'preflight');
  }

  if (branchExists(branchName)) {
    throw new DraftPrError(`Branch ${branchName} already exists`, 'preflight');
  }

  if (isDryRun) {
    return { branchName, commitSha: null, prUrl: null, dryRun: true };
  }

  // 2. Create branch, apply patch, commit, push, open PR
  const tmpPatchPath = join(REPO_ROOT, `.bug-resolver-tmp-${Date.now()}.patch`);
  let commitSha = null;
  let prUrl = null;
  // v2 (2026-05-25): hoist these so the return statement can surface them.
  let autoMergeSafe = false;
  let sensitiveTouches = [];

  try {
    run(`git checkout -b ${branchName}`);

    writeFileSync(tmpPatchPath, patch);
    run(`git apply ${tmpPatchPath}`);

    // Add only the files the patch touched (NEVER git add -A — that would
    // accidentally stage unrelated untracked files Mitchell may have).
    // Parse diff headers to get touched paths.
    const touchedFiles = [];
    for (const line of patch.split('\n')) {
      const m = line.match(/^diff --git a\/(\S+) b\/(\S+)/);
      if (m) touchedFiles.push(m[2]); // post-image path
    }
    if (touchedFiles.length === 0) {
      throw new DraftPrError('patch contains no "diff --git" file headers', 'commit');
    }
    for (const f of touchedFiles) {
      run(`git add -- ${JSON.stringify(f)}`);
    }

    const commitMsg = formatCommitMessage(bugId, prMetadata);
    // Use heredoc-style commit via -F - to handle multi-line + special chars safely
    run(`git commit -F -`, { input: commitMsg });
    commitSha = run('git rev-parse HEAD').trim();

    // 3. Push
    run(`git push -u origin ${branchName}`);

    // v2 (2026-05-25): auto-merge gating. Per interview Q3 + Q4 — all
    // bug-resolver PRs auto-merge on CI green EXCEPT those touching any
    // path matching the cross-fork-leak sensitive-paths regex. Sensitive
    // touches stay DRAFT-only for human review.
    if (enableAutoMerge) {
      sensitiveTouches = findSensitiveTouches(touchedFiles);
      autoMergeSafe = sensitiveTouches.length === 0;
      if (!autoMergeSafe) {
        // eslint-disable-next-line no-console
        console.log(
          `[draft-pr] auto-merge BLOCKED for ${bugId} — sensitive paths touched: ` +
          sensitiveTouches.join(', ')
        );
      } else {
        // eslint-disable-next-line no-console
        console.log(`[draft-pr] auto-merge ENABLED for ${bugId} — no sensitive paths`);
      }
    }

    // 4. Open DRAFT PR via safe-gh-pr.sh
    // If autoMergeSafe, pass --auto-merge-after-ci so the wrapper chains
    // `gh pr merge --auto --squash` after the create call returns.
    const prBody = formatPrBody(bugId, prMetadata, autoMergeSafe);
    const prTitle = prMetadata.title;
    const autoMergeFlag = autoMergeSafe ? '--auto-merge-after-ci ' : '';
    const ghOut = run(
      `bash scripts/safe-gh-pr.sh --draft ${autoMergeFlag}--title ${JSON.stringify(prTitle)} --body-file -`,
      { input: prBody }
    );
    // gh pr create outputs the URL on stdout (URL line first, then optional
    // auto-merge log lines from the wrapper). Pick the first URL line.
    const urlLine = ghOut.split('\n').find(s => /^https?:\/\//.test(s.trim()));
    prUrl = urlLine ? urlLine.trim() : '';
  } catch (err) {
    // Cleanup partial state — checkout main + delete the bad branch
    try { run('git checkout main'); } catch {}
    try { run(`git branch -D ${branchName}`); } catch {}
    throw new DraftPrError(`createDraftPr failed: ${err.message}`, 'execute');
  } finally {
    // Cleanup temp patch file
    try { if (existsSync(tmpPatchPath)) unlinkSync(tmpPatchPath); } catch {}
    // Always return to main when done (safe even on success path)
    try { run('git checkout main'); } catch {}
  }

  return {
    branchName,
    commitSha,
    prUrl,
    autoMergeSafe,
    sensitiveTouches,
  };
}
