// AUTO-GENERATED by scripts/transform-tokens.mjs — DO NOT EDIT.
// Source: tokens/master.json
// Master hash (sha256): a9b8abd436b489b79405f9cac536e5ac3eb09a953a3dee21509b4abec1cbbca2
// Schema version: 1.0.0
// Re-run: node scripts/transform-tokens.mjs
// Helpers (scoreBadgeColors, statusBadgeColors, missionControlHeader, emailDarkCss)
// live in lib/dashboard-token-helpers.mjs.

export const TOKENS = {
  "dark": {
    "amber": "#d4ba84",
    "amberBg": "rgba(168,123,72,0.14)",
    "amberFg": "#d4ba84",
    "backdrop": [
      "radial-gradient(ellipse 1200px 600px at 12% -10%, rgba(64, 224, 208, 0.06), transparent 60%)",
      "radial-gradient(ellipse 900px 500px at 88% 110%, rgba(139, 92, 246, 0.05), transparent 65%)",
      "radial-gradient(ellipse 700px 400px at 50% 50%, rgba(0, 255, 157, 0.025), transparent 70%)"
    ],
    "bg": "#06070d",
    "blue": "#94a3b8",
    "blueBg": "rgba(100,116,139,0.14)",
    "blueFg": "#94a3b8",
    "border": "#232737",
    "borderStrong": "#353a52",
    "green": "#4ade80",
    "greenBg": "rgba(22,163,74,0.12)",
    "greenBorder": "rgba(22,163,74,0.30)",
    "greenFg": "#86efac",
    "greenFgDark": "#bbf7d0",
    "greenGlow": "rgba(74,222,128,0.35)",
    "red": "#fca5a5",
    "redBg": "rgba(220,38,38,0.12)",
    "redFg": "#fca5a5",
    "surface": "#11131c",
    "surface2": "#181b27",
    "text": "#fafafa",
    "text2": "#e4e4e7",
    "text3": "#b8b8c0",
    "text4": "#9a9aa6"
  },
  "email": {
    "amberBg": "#f4ede1",
    "amberFg": "#a87b48",
    "bg": "#ffffff",
    "blue": "#5a76a6",
    "blueBg": "#e8edf4",
    "blueFg": "#5a76a6",
    "border": "#e5e7eb",
    "borderStrong": "#d1d5db",
    "green": "#15803d",
    "greenBg": "#dcfce7",
    "greenBorder": "#86efac",
    "greenFg": "#166534",
    "redBg": "#fee2e2",
    "redFg": "#dc2626",
    "surface": "#ffffff",
    "surface2": "#f1f5f9",
    "text": "#111827",
    "text2": "#374151",
    "text3": "#475569",
    "text4": "#6b7280"
  }
};
