// AUTO-GENERATED by scripts/transform-tokens.mjs — DO NOT EDIT.
// Source: tokens/master.json typography.role.* (email fontSize path)
// Master hash (sha256): 4061aa94720566d0c6877d40692b113d3cbc2d0bca58615478581316609ec7d6
// Schema version: 1.1.0
// Re-run: node scripts/transform-tokens.mjs
//
// Web fontSize path lives in dashboard/css/tokens.css as .t-{role} classes.
// styleString() converts a role + overrides into an email-safe inline-style
// string (no media queries, no CSS vars — Outlook strips both).

export const TYPE_ROLES = Object.freeze({
  h1: Object.freeze({
    fontSize: "22px",
    fontWeight: "700",
    lineHeight: "1.2",
    letterSpacing: "-0.01em",
    fontFamily: "Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif"
  }),
  h2: Object.freeze({
    fontSize: "16px",
    fontWeight: "700",
    lineHeight: "1.3",
    letterSpacing: "-0.3px",
    fontFamily: "Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif"
  }),
  h3: Object.freeze({
    fontSize: "13px",
    fontWeight: "700",
    lineHeight: "1.3",
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    fontFamily: "Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif"
  }),
  sectionLabel: Object.freeze({
    fontSize: "10px",
    fontWeight: "700",
    lineHeight: "1.3",
    letterSpacing: "0.10em",
    textTransform: "uppercase",
    fontFamily: "Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif"
  }),
  bodyLarge: Object.freeze({
    fontSize: "15px",
    fontWeight: "600",
    lineHeight: "1.4",
    fontFamily: "Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif"
  }),
  body: Object.freeze({
    fontSize: "13px",
    fontWeight: "400",
    lineHeight: "1.5",
    fontFamily: "Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif"
  }),
  bodySmall: Object.freeze({
    fontSize: "12px",
    fontWeight: "400",
    lineHeight: "1.4",
    fontFamily: "Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif"
  }),
  meta: Object.freeze({
    fontSize: "11px",
    fontWeight: "500",
    lineHeight: "1.3",
    letterSpacing: "0.01em",
    fontFamily: "Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif"
  }),
  code: Object.freeze({
    fontSize: "12px",
    fontWeight: "400",
    lineHeight: "1.4",
    fontFamily: "'JetBrains Mono', 'IBM Plex Mono', 'SF Mono', SFMono-Regular, Menlo, Monaco, Consolas, monospace"
  }),
  buttonLabel: Object.freeze({
    fontSize: "12px",
    fontWeight: "600",
    lineHeight: "1",
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    fontFamily: "Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif"
  })
});

/**
 * Converts a TYPE_ROLES entry + overrides into an email-safe inline-style string.
 *
 * @param {Readonly<Record<string, string>>} roleProps  one TYPE_ROLES entry
 * @param {Record<string, string>} [overrides]  e.g. { color: '#86efac', margin: '10px 0 3px' }
 * @returns {string}  e.g. 'font-size:10px;font-weight:700;color:#86efac;margin:10px 0 3px'
 *
 * - Keys are emitted in role-then-overrides order (overrides win on collision).
 * - 'textTransform: none' and 'letterSpacing: normal' are suppressed (no-op in email).
 * - Never emits a 'color:' from the role itself — color is always an override.
 * - Output is a single line; no trailing semicolon; ready to drop into style="...".
 */
export function styleString(roleProps, overrides = {}) {
  const merged = { ...roleProps, ...overrides };
  return Object.entries(merged)
    .filter(([, v]) => v !== undefined && v !== null && v !== 'none' && v !== 'normal')
    .map(([k, v]) => camelToKebab(k) + ':' + v)
    .join(';');
}

function camelToKebab(s) {
  return s.replace(/([A-Z])/g, m => '-' + m.toLowerCase());
}
