/**
 * lib/github-cleaner/implement.mjs — Phase 5 of github-cleaner.
 *
 * Self-implements the Phase 4-gated artifacts via gh CLI. Enforces every
 * hard-gate from the design doc:
 *   - PRs only via gh pr create --repo <explicit> (refuses cross-fork)
 *   - Never push to upstream (santifer)
 *   - Never force-push
 *   - Never delete a repo (archive only)
 *   - Prompt before making private→public, identity changes, popular repos
 *
 * Output: per-action log at data/github-cleaner/<TS>/implement-log.jsonl
 *
 * See: data/github-cleaner-design-2026-05-22.md § Phase 5.
 */

import { execFileSync, spawnSync } from 'node:child_process';
import { existsSync, writeFileSync, appendFileSync, mkdirSync, mkdtempSync, rmSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { tmpdir } from 'node:os';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..', '..');

const SAFE_GH_PR = join(ROOT, 'scripts', 'safe-gh-pr.sh');
const SAFE_REPO = 'mitwilli-create/career-ops';
const UPSTREAM_REFUSAL_PATTERN = /santifer\/career-ops/i;

const DESIGN_DOC_REF = 'data/github-cleaner-design-2026-05-22.md § Phase 5';

function emit(obj) {
  process.stderr.write(JSON.stringify({ t: new Date().toISOString(), phase: 'implement', ...obj }) + '\n');
}

/**
 * Pre-flight refusal check on every action.
 */
export function checkHardGates({ action, target, confirmFlags } = {}) {
  if (action === 'push_upstream') return { gate: 'cross_fork', reason: 'refuse — santifer is upstream', override_flag: null };
  if (action === 'force_push') return { gate: 'force_push', reason: 'refuse — destructive', override_flag: null };
  if (action === 'delete_repo') return { gate: 'delete_repo', reason: 'refuse — archive is reversible alternative', override_flag: null };
  if (action === 'make_public' && !confirmFlags?.[`confirm_make_public_${target}`]) {
    return { gate: 'visibility_change', reason: 'requires --confirm-make-public', override_flag: `--confirm-make-public ${target}` };
  }
  if (action === 'change_identity' && !confirmFlags?.confirm_identity_change) {
    return { gate: 'identity_change', reason: 'requires --confirm-identity-change', override_flag: '--confirm-identity-change' };
  }
  if (action === 'popular_repo' && !confirmFlags?.[`confirm_popular_repo_${target}`]) {
    return { gate: 'popular_repo', reason: '>50 stars — requires --confirm-popular-repo', override_flag: `--confirm-popular-repo ${target}` };
  }
  return null;
}

/**
 * Append one entry to the implement-log.jsonl.
 */
export function logAction(logPath, entry) {
  mkdirSync(dirname(logPath), { recursive: true });
  appendFileSync(logPath, JSON.stringify({ t: new Date().toISOString(), ...entry }) + '\n', 'utf-8');
}

/**
 * Implement one artifact. Dispatches by kind to the appropriate gh action.
 *
 * @param {{ artifact: object, recommendation: object, logPath: string, confirmFlags: object }} args
 * @returns {Promise<{ ok: boolean, action: string, result: string, refused?: string }>}
 */
export async function implementArtifact(args) {
  const { artifact, recommendation, logPath, confirmFlags = {} } = args;
  const { scope, target, recommendation: kind } = recommendation;
  const { content } = artifact;

  emit({ step: 'dispatch', scope, target, kind });

  // Popular repo check
  const repo = null; // would look up from inventory, but guarded by caller
  // For popular repo gate, the orchestrator must pass confirmFlags

  const logEntry = { scope, target, kind, artifact_kind: kind };

  try {
    let result;
    if (kind === 'SECURITY-INCIDENT') {
      const refusal = { gate: 'security_incident', reason: 'Security incident detected — no implementation allowed. Address the secret exposure first.' };
      logAction(logPath, { ...logEntry, action: 'refused', refusal });
      return { ok: false, action: 'refused', refused: refusal.reason };
    }

    if (kind === 'ARCHIVE') {
      const reason = recommendation.rationale || 'stale or low-signal repo';
      result = await archiveRepo(target, reason);
      logAction(logPath, { ...logEntry, action: 'archived', result: result.ok ? 'ok' : result.error });
      return { ok: result.ok, action: 'archived', result: result.message, repo: target };
    }

    if (scope === 'profile' || target === 'profile') {
      if (kind === 'REWRITE-README' || kind === 'RESTRUCTURE') {
        const handle = target.split('/')[0] || 'mitwilli-create';
        result = await commitAndPR({
          repoSlug: `${handle}/${handle}`,
          branchName: `cleanup/profile-readme-${new Date().toISOString().slice(0, 10)}`,
          filePathInRepo: 'README.md',
          content,
          title: `hiring-readiness: refresh profile README`,
          body: `Auto-generated by github-cleaner. Recommendation: ${kind}\n\nRationale: ${recommendation.rationale || ''}`,
        });
        logAction(logPath, { ...logEntry, action: result.action, pr_url: result.pr_url });
        return { ok: result.ok, action: result.action, pr_url: result.pr_url, repo: `${handle}/${handle}` };
      }
      if (kind === 'ADD-DOCS') {
        // Update bio
        result = await updateBio(content.slice(0, 160), confirmFlags);
        logAction(logPath, { ...logEntry, action: 'bio_updated', result: result.ok ? 'ok' : result.error });
        return { ok: result.ok, action: 'bio_updated' };
      }
    }

    if (kind === 'REWRITE-README' || kind === 'ADD-DOCS' || kind === 'RESTRUCTURE') {
      result = await commitAndPR({
        repoSlug: target,
        branchName: `cleanup/hiring-readiness-${new Date().toISOString().slice(0, 10)}`,
        filePathInRepo: 'README.md',
        content,
        title: `hiring-readiness: ${kind.toLowerCase().replace(/-/g, ' ')} ${target.split('/')[1]}`,
        body: `Auto-generated by github-cleaner.\n\nRecommendation: ${kind}\nRationale: ${recommendation.rationale || ''}\n\nFindings addressed:\n${(recommendation.findings || []).map(f => `- ${f.evidence}`).join('\n')}`,
      });
      logAction(logPath, { ...logEntry, action: result.action, pr_url: result.pr_url });
      return { ok: result.ok, action: result.action, pr_url: result.pr_url, repo: target };
    }

    // Default: description update
    if (content && content.length < 350) {
      result = await updateRepoDescription(target, content);
      logAction(logPath, { ...logEntry, action: 'description_updated', result: result.ok ? 'ok' : result.error });
      return { ok: result.ok, action: 'description_updated', repo: target };
    }

    logAction(logPath, { ...logEntry, action: 'no_op', note: `kind ${kind} not mapped to an implementation action` });
    return { ok: true, action: 'no_op', note: `kind ${kind} not mapped` };
  } catch (e) {
    const error = String(e.message).slice(0, 300);
    logAction(logPath, { ...logEntry, action: 'error', error });
    emit({ step: 'error', scope, target, kind, error });
    return { ok: false, action: 'error', error };
  }
}

/**
 * Commit + PR a README/docs change. Always passes --repo explicitly to gh.
 * Branch name: cleanup/hiring-readiness-<YYYY-MM-DD>.
 */
export async function commitAndPR({ repoSlug, branchName, filePathInRepo, content, title, body }) {
  emit({ step: 'commit_pr_start', repo: repoSlug, branch: branchName });

  // Hard-gate: refuse if repoSlug matches upstream pattern
  if (UPSTREAM_REFUSAL_PATTERN.test(repoSlug)) {
    throw new Error(`commitAndPR: REFUSED — ${repoSlug} matches upstream (santifer). Cross-fork guard active.`);
  }

  // For career-ops, use safe-gh-pr.sh. For other repos, use gh pr create --repo explicitly.
  const isCareerOps = repoSlug === SAFE_REPO;

  let tmpDir;
  try {
    // Create temp working directory
    tmpDir = mkdtempSync(join(tmpdir(), 'gc-pr-'));

    // Clone the repo
    emit({ step: 'cloning', repo: repoSlug, tmpDir });
    execFileSync('gh', ['repo', 'clone', repoSlug, tmpDir, '--', '--depth=1'], {
      encoding: 'utf-8', timeout: 120_000, stdio: ['pipe', 'pipe', 'pipe'],
    });

    // Create + checkout branch
    execFileSync('git', ['-C', tmpDir, 'checkout', '-b', branchName], {
      encoding: 'utf-8', timeout: 10_000,
    });

    // Write the file
    const filePath = join(tmpDir, filePathInRepo);
    mkdirSync(dirname(filePath), { recursive: true });
    writeFileSync(filePath, content, 'utf-8');

    // Stage by filename (never git add -A)
    execFileSync('git', ['-C', tmpDir, 'add', filePathInRepo], {
      encoding: 'utf-8', timeout: 10_000,
    });

    // Check if there's actually a diff
    const diffResult = spawnSync('git', ['-C', tmpDir, 'diff', '--cached', '--quiet'], { timeout: 10_000 });
    if (diffResult.status === 0) {
      emit({ step: 'no_diff', repo: repoSlug, file: filePathInRepo });
      return { ok: true, action: 'no_change', message: 'File unchanged — no PR needed' };
    }

    // Commit
    execFileSync('git', ['-C', tmpDir, 'commit', '-m', `hiring-readiness: ${title}`], {
      encoding: 'utf-8', timeout: 10_000,
      env: { ...process.env, GIT_AUTHOR_NAME: 'github-cleaner', GIT_AUTHOR_EMAIL: 'github-cleaner@career-ops', GIT_COMMITTER_NAME: 'github-cleaner', GIT_COMMITTER_EMAIL: 'github-cleaner@career-ops' },
    });

    // Push branch
    execFileSync('git', ['-C', tmpDir, 'push', 'origin', branchName], {
      encoding: 'utf-8', timeout: 30_000,
    });

    // Create PR — always explicit --repo
    let prUrl;
    if (isCareerOps && existsSync(SAFE_GH_PR)) {
      const prResult = spawnSync('bash', [
        SAFE_GH_PR,
        '--title', title,
        '--body', body || '',
        '--head', branchName,
        '--draft',
      ], { encoding: 'utf-8', timeout: 30_000, cwd: tmpDir });
      const output = (prResult.stdout || '') + (prResult.stderr || '');
      const urlMatch = output.match(/https:\/\/github\.com\/[^\s]+\/pull\/\d+/);
      prUrl = urlMatch ? urlMatch[0] : null;
      if (prResult.status !== 0 && !prUrl) {
        throw new Error(`safe-gh-pr.sh failed: ${output.slice(0, 300)}`);
      }
    } else {
      const prResult = spawnSync('gh', [
        'pr', 'create',
        '--repo', repoSlug,
        '--title', title,
        '--body', body || '',
        '--head', branchName,
        '--draft',
      ], { encoding: 'utf-8', timeout: 30_000, cwd: tmpDir });
      const output = (prResult.stdout || '') + (prResult.stderr || '');
      const urlMatch = output.match(/https:\/\/github\.com\/[^\s]+\/pull\/\d+/);
      prUrl = urlMatch ? urlMatch[0] : null;
      if (prResult.status !== 0 && !prUrl) {
        emit({ step: 'pr_create_warn', output: output.slice(0, 300) });
        // Non-fatal — branch was pushed, PR creation might have partially succeeded
      }
    }

    emit({ step: 'pr_created', repo: repoSlug, branch: branchName, pr_url: prUrl });
    return { ok: true, action: prUrl ? 'pr_opened' : 'branch_pushed', pr_url: prUrl };
  } catch (e) {
    emit({ step: 'commit_pr_error', repo: repoSlug, error: String(e.message).slice(0, 300) });
    throw e;
  } finally {
    if (tmpDir && existsSync(tmpDir)) {
      try { rmSync(tmpDir, { recursive: true, force: true }); } catch { /* cleanup failure is non-fatal */ }
    }
  }
}

/**
 * gh repo edit <repo> --description "...".
 */
export async function updateRepoDescription(repoSlug, description) {
  if (UPSTREAM_REFUSAL_PATTERN.test(repoSlug)) {
    return { ok: false, error: `REFUSED — ${repoSlug} matches upstream` };
  }
  const truncated = (description || '').slice(0, 350).trim();
  try {
    execFileSync('gh', ['repo', 'edit', repoSlug, '--description', truncated], {
      encoding: 'utf-8', timeout: 15_000,
    });
    emit({ step: 'description_updated', repo: repoSlug });
    return { ok: true, action: 'description_updated' };
  } catch (e) {
    return { ok: false, error: String(e.message).slice(0, 200) };
  }
}

/**
 * Set repo topics. One gh call to replace all topics at once.
 */
export async function setRepoTopics(repoSlug, topicsToAdd, topicsToRemove = []) {
  if (UPSTREAM_REFUSAL_PATTERN.test(repoSlug)) {
    return { ok: false, error: `REFUSED — ${repoSlug} matches upstream` };
  }
  try {
    // Get current topics first
    const raw = execFileSync('gh', ['api', `repos/${repoSlug}/topics`], {
      encoding: 'utf-8', timeout: 10_000,
    });
    const current = JSON.parse(raw).names || [];
    const removeSet = new Set(topicsToRemove.map(t => t.toLowerCase()));
    const addSet = new Set((topicsToAdd || []).map(t => t.toLowerCase().replace(/\s+/g, '-')));
    const updated = [...new Set([
      ...current.filter(t => !removeSet.has(t.toLowerCase())),
      ...addSet,
    ])].slice(0, 20); // GitHub limit is 20 topics

    execFileSync('gh', ['api', '-X', 'PUT', `repos/${repoSlug}/topics`,
      '--input', '-'],
      {
        encoding: 'utf-8', timeout: 15_000,
        input: JSON.stringify({ names: updated }),
      }
    );
    emit({ step: 'topics_updated', repo: repoSlug, topics: updated });
    return { ok: true, action: 'topics_updated', topics: updated };
  } catch (e) {
    return { ok: false, error: String(e.message).slice(0, 200) };
  }
}

/**
 * Archive a repo (reversible — does NOT delete).
 */
export async function archiveRepo(repoSlug, archiveReason) {
  if (UPSTREAM_REFUSAL_PATTERN.test(repoSlug)) {
    return { ok: false, error: `REFUSED — ${repoSlug} matches upstream` };
  }
  try {
    execFileSync('gh', ['api', '-X', 'PATCH', `repos/${repoSlug}`,
      '-f', 'archived=true'],
      { encoding: 'utf-8', timeout: 15_000 }
    );
    emit({ step: 'archived', repo: repoSlug, reason: archiveReason });
    return { ok: true, action: 'archived', message: `Archived ${repoSlug}: ${archiveReason}` };
  } catch (e) {
    return { ok: false, error: String(e.message).slice(0, 200) };
  }
}

/**
 * Update pinned repos via GitHub GraphQL API.
 * Requires the user:profile scope on the GH token.
 */
export async function setPinnedRepos(orderedRepoNames) {
  if (!orderedRepoNames || orderedRepoNames.length === 0) {
    return { ok: false, error: 'No repos specified' };
  }
  try {
    // Get user login first
    const userRaw = execFileSync('gh', ['api', 'user', '--jq', '.login'], {
      encoding: 'utf-8', timeout: 10_000,
    }).trim();

    // Get repo IDs for each named repo
    const repoIds = [];
    for (const name of orderedRepoNames.slice(0, 6)) {
      try {
        const slug = name.includes('/') ? name : `${userRaw}/${name}`;
        const raw = execFileSync('gh', ['api', `repos/${slug}`, '--jq', '.node_id'], {
          encoding: 'utf-8', timeout: 10_000,
        }).trim();
        if (raw) repoIds.push(raw);
      } catch { /* skip repos that don't exist */ }
    }

    if (repoIds.length === 0) {
      return { ok: false, error: 'Could not resolve any repo node IDs' };
    }

    // GraphQL mutation to update pinned repos
    const itemIds = repoIds.map(id => `"${id}"`).join(', ');
    const mutation = `mutation { updatePinnableItems(input: { clientMutationId: "gc-pin", pinnableItemIds: [${itemIds}] }) { clientMutationId } }`;
    execFileSync('gh', ['api', 'graphql', '-f', `query=${mutation}`], {
      encoding: 'utf-8', timeout: 15_000,
    });
    emit({ step: 'pinned_updated', repos: orderedRepoNames.slice(0, 6) });
    return { ok: true, action: 'pinned_updated', repos: orderedRepoNames.slice(0, 6) };
  } catch (e) {
    return { ok: false, error: String(e.message).slice(0, 200) };
  }
}

/**
 * Update profile bio.
 */
export async function updateBio(newBio, confirmFlags = {}) {
  const truncated = (newBio || '').slice(0, 160).trim();
  if (!truncated) return { ok: false, error: 'Empty bio' };
  try {
    execFileSync('gh', ['api', '-X', 'PATCH', 'user', '-f', `bio=${truncated}`], {
      encoding: 'utf-8', timeout: 15_000,
    });
    emit({ step: 'bio_updated', length: truncated.length });
    return { ok: true, action: 'bio_updated' };
  } catch (e) {
    return { ok: false, error: String(e.message).slice(0, 200) };
  }
}

export { SAFE_GH_PR, SAFE_REPO, UPSTREAM_REFUSAL_PATTERN };
